name: 'Update Issue Body'
description: 'Update an issue body'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
  repository:
    description: 'The full name of the repository in which to create or update a comment.'
    default: ${{ github.repository }}
  issue-number:
    description: 'The number of the issue to be updated.'
  body:
    description: 'The issue body.'
  edit-mode:
    description: 'The mode when updating the issue body, "replace", "append" or "prepend".'
    default: 'append'
  prepend-separator:
    description: 'The separator to use when prepending to an existing issue body. (`newline`, `space`, `none`)'
    default: 'newline'
  append-separator:
    description: 'The separator to use when appending to an existing issue body. (`newline`, `space`, `none`)'
    default: 'newline'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'message-square'
  color: 'gray-dark'
